# Generated by Django 4.2.5 on 2023-09-04 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_application', '0002_thing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
