# Generated by Django 4.2.5 on 2023-09-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_application', '0003_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
